---
- hosts: git0*
  gather_facts: false
  max_fail_percentage: 1
  roles:
    - { role: puppet, puppetmaster: puppetmaster.openswitch.net }
- hosts: review.openswitch.net
  gather_facts: false
  roles:
    - { role: puppet, puppetmaster: puppetmaster.openswitch.net }
